### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by WangYixuan12** [ritalaezza/gym-agx#4]
Hi! Thanks for this fantastic work! It seems to match my research need perfectly. However, it seems the backend simulator AGX is not open-sourced. I am wondering whether it is required to obtain a license for AGX to run this project.

**Comment by ritalaezza** [comment]
Hi! Yes, you need to obtain a license for AGX Dynamics to run this project. However, Algoryx is also quite open for collaboration, in case the price is prohibitive for you. So don't hesitate to contact them about your research project.
